version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: test_rabbitmq
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${DEFAULT_PASS}
#    volumes:
#      - ./config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
#      - ./config/definitions.json:/etc/rabbitmq/definitions.json
